apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot004
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhdh-pai-qe/chatbot:55e640404f1f8e37a437644b8931ce669b6b628a@sha256:f482b3b71827687ef2c9932409f040d36888255f8b38250a7417c4ecf59cb252 # use pre-built to bootstrap
          name: app-inference
