apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot004
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot004
  name: chatbot004
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
