apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: chatbot004
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot004
  name: chatbot004
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: chatbot004
    weight: 100
  wildcardPolicy: None
