apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chatbot004
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot004
  name: chatbot004
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chatbot004
